name: Run Windows container
on:
  push:
    branches:
      - check-container-run

permissions:
  contents: read

jobs:
  check_run_windows_container:
    name: Test Alloy Windows container
    runs-on: windows-2025
    steps:
    - name: Build and publish the container
      run: |
        docker run --detach --name alloyTest ptodev/alloy:latest
        Write-Host "Sleeping..."
        Start-Sleep -Seconds 10
        docker logs alloyTest
        Start-Sleep -Seconds 10
        docker logs alloyTest
