name: Run Windows container
on:
  push:
    branches:
      - check-container-run

permissions:
  contents: read

jobs:
  check_run_windows_container:
    name: Test Alloy Windows container
    strategy:
      matrix:
        image:
        - ptodev/alloy-dev:nanoserver-1809
        - ptodev/alloy-dev:windowsservercore-ltsc2022
        - ptodev/alloy-dev:windowsservercore-ltsc2025
    runs-on: windows-2025
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and publish the container
      run: |
        docker run --detach --name alloyTest ${{ matrix.image}} --isolation=hyperv

        Write-Host "Checking if the container is running..."
        $success = false
        $log = ""
        $i=1
        for(;$i -le 60;$i++)
        {
          Start-Sleep -Seconds 1
          $log = docker logs alloyTest
          if ($log -contains "finished node evaluation")
          {
            $success = $true
            Write-Host "Container is running successfully."
            break
          }
        }

        if ($success)
        {
          Write-Host "Container ran successfully."
          Write-Host "Container failed to run. Check the logs for more details:\n", $log 
        }
        else
        {
          Write-Error "Container failed to run. Check the logs for more details:\n", $log 
          exit 1
        }
