name: Publish alloy release containers
on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish_linux_container:
    uses: ./.github/workflows/publish-alloy-linux.yml
    permissions:
      contents: read
      id-token: write
    with:
      img-name: alloy
  
  publish_linux_boringcrypto_container:
    uses: ./.github/workflows/publish-alloy-linux.yml
    permissions:
      contents: read
      id-token: write
    with:
      img-name: alloy-boringcrypto

  publish_windows_container:
    uses: ./.github/workflows/publish-alloy-windows.yml
    permissions:
      contents: read
      id-token: write
    with:
      img-name: alloy
